### ISSUE TITLE
问题严重

### ISSUE THREAD

**Issue by hjun0907** [yeraph-plus/alist-client-plugin-for-wordpress#1]
赶紧更新 整个后台都打不开

**Comment by yeraph-plus** [comment]
不需要修改代码就用Releases里的版本。

**Comment by hjun0907** [comment]
后台打不开

Fatal error: Uncaught TypeError: strpos(): Argument #1 ($haystack) must be of type string, array given in /www/wwwroot/blog.xxxx.xyz/wp-content/plugins/alist-client-plugin-for-wordpress/inc/method-public.php:27 Stack trace: #0 /www/wwwroot/blog.xxxx.xyz/wp-content/plugins/alist-client-plugin-for-wordpress/inc/method-public.php(27): strpos() #1 /www/wwwroot/blog.xxxx.xyz/wp-content/plugins/alist-client-plugin-for-wordpress/inc/method-public.php(83): aya_alist_request_token() #2 /www/wwwroot/blog.xxxx.xyz/wp-content/plugins/alist-client-plugin-for-wordpress/inc/method-public.php(108): aya_alist_get_token() #3 /www/wwwroot/blog.xxxx.xyz/wp-content/plugins/alist-client-plugin-for-wordpress/plugin-build-framework-options.php(158): aya_alist_server_list_request() #4 /www/wwwroot/blog.xxxx.xyz/wp-includes/class-wp-hook.php(324): aya_alist_server_option() #5 /www/wwwroot/blog.xxxx.xyz/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters() #6 /www/wwwroot/blog.xxxx.xyz/wp-includes/plugin.php(517): WP_Hook->do_action() #7 /www/wwwroot/blog.xxxx.xyz/wp-settings.php(682): do_action() #8 /www/wwwroot/blog.xxxx.xyz/wp-config.php(102): require_once('...') #9 /www/wwwroot/blog.xxxx.xyz/wp-load.php(50): require_once('...') #10 /www/wwwroot/blog.xxxx.xyz/wp-admin/admin.php(34): require_once('...') #11 /www/wwwroot/blog.xxxx.xyz/wp-admin/plugins.php(10): require_once('...') #12 {main} thrown in /www/wwwroot/blog.xxxx.xyz/wp-content/plugins/alist-client-plugin-for-wordpress/inc/method-public.php on line 27

**Comment by hjun0907** [comment]
后台打不开

Fatal error: Uncaught TypeError: strpos(): Argument #1 ($haystack) must be of type string, array given in /www/wwwroot/blog.xxxx.xyz/wp-content/plugins/alist-client-plugin-for-wordpress/inc/method-public.php:27 Stack trace: #0 /www/wwwroot/blog.xxxx.xyz/wp-content/plugins/alist-client-plugin-for-wordpress/inc/method-public.php(27): strpos() #1 /www/wwwroot/blog.xxxx.xyz/wp-content/plugins/alist-client-plugin-for-wordpress/inc/method-public.php(83): aya_alist_request_token() #2 /www/wwwroot/blog.xxxx.xyz/wp-content/plugins/alist-client-plugin-for-wordpress/inc/method-public.php(108): aya_alist_get_token() #3 /www/wwwroot/blog.xxxx.xyz/wp-content/plugins/alist-client-plugin-for-wordpress/plugin-build-framework-options.php(158): aya_alist_server_list_request() #4 /www/wwwroot/blog.xxxx.xyz/wp-includes/class-wp-hook.php(324): aya_alist_server_option() #5 /www/wwwroot/blog.xxxx.xyz/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters() #6 /www/wwwroot/blog.xxxx.xyz/wp-includes/plugin.php(517): WP_Hook->do_action() #7 /www/wwwroot/blog.xxxx.xyz/wp-settings.php(682): do_action() #8 /www/wwwroot/blog.xxxx.xyz/wp-config.php(102): require_once('...') #9 /www/wwwroot/blog.xxxx.xyz/wp-load.php(50): require_once('...') #10 /www/wwwroot/blog.xxxx.xyz/wp-admin/admin.php(34): require_once('...') #11 /www/wwwroot/blog.xxxx.xyz/wp-admin/plugins.php(10): require_once('...') #12 {main} thrown in /www/wwwroot/blog.xxxx.xyz/wp-content/plugins/alist-client-plugin-for-wordpress/inc/method-public.php on line 27

**Comment by yeraph-plus** [comment]
看报错的位置应该是wp的目录php没有写文件的权限。插件会用wp的缓存方法在数据库里创建一个缓存索引。如果是由于其他原因禁用了WP缓存，则需要创建一个缓存文件保存这些数据。这个缓存中是alist的token数据，主要是防止频繁请求alist的认证接口。
